version: 0.1

default:
  global:
    parameters:
      stack_name: event-platform-auth
      region: eu-north-1
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      resolve_s3: true
      parameter_overrides:
        - MongoDbUri=YOUR_MONGODB_URI
        - OidcAudience=YOUR_OIDC_AUDIENCE
