AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Event Platform - ACM Certificate (us-east-1)

Parameters:
  DomainName:
    Type: String
    Description: Root domain name
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}:certificate-arn
